namespace Quiz.Application.UseCases.Games.GetMultipleChoiceQuestions;

public sealed record GetMultipleChoiceQuestionsResponse(Guid GameId, IReadOnlyCollection<MultipleChoiceQuestionResponse> Questions);